# Generated by Django 3.0.7 on 2020-06-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerConsole', '0002_auto_20200627_0318'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HockeyPlayer',
            new_name='Player',
        ),
    ]
