# Generated by Django 3.0.7 on 2020-06-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerConsole', '0004_player_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='F', max_length=2),
            preserve_default=False,
        ),
    ]
