# Generated by Django 3.0.7 on 2020-06-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerConsole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hockeyplayer',
            old_name='player_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='hockeyplayer',
            old_name='player_name',
            new_name='name',
        ),
    ]
