# Generated by Django 3.0.7 on 2020-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerConsole', '0003_auto_20200627_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='Russian', max_length=50),
            preserve_default=False,
        ),
    ]
