# Generated by Django 3.1.4 on 2020-12-23 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerConsole', '0006_auto_20201223_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playerseasonstats',
            options={'managed': False},
        ),
    ]
